# Import Libraries

In [22]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

import torch

## breast Cancer dataset

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

# EDA

In [6]:
df.shape

(569, 33)

In [7]:
df.describe()

                 id  radius_mean  ...  fractal_dimension_worst  Unnamed: 32
count  5.690000e+02   569.000000  ...               569.000000          0.0
mean   3.037183e+07    14.127292  ...                 0.083946          NaN
std    1.250206e+08     3.524049  ...                 0.018061          NaN
min    8.670000e+03     6.981000  ...                 0.055040          NaN
25%    8.692180e+05    11.700000  ...                 0.071460          NaN
50%    9.060240e+05    13.370000  ...                 0.080040          NaN
75%    8.813129e+06    15.780000  ...                 0.092080          NaN
max    9.113205e+08    28.110000  ...                 0.207500          NaN

[8 rows x 32 columns]

>id, Unnamed unnecessary  column

In [8]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

df.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [9]:
df.head(7)

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678
5         M        12.45  ...          0.3985                  0.12440
6         M        18.25  ...          0.3063                  0.08368

[7 rows x 31 columns]

## Split the dataset

In [24]:
X_train ,X_test , y_train , y_test = train_test_split(
                                                   df.iloc[:,1 : ],
                                                   df.iloc[:,0],
                                                   test_size=0.2
                                                   )

In [25]:
print(X_train)

     radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
199       14.450         20.22  ...          0.4753                  0.10130
484       15.730         11.28  ...          0.2557                  0.08181
435       13.980         19.62  ...          0.3179                  0.10550
379       11.080         18.83  ...          0.4154                  0.14030
312       12.760         13.37  ...          0.2564                  0.08253
..           ...           ...  ...             ...                      ...
533       20.470         20.67  ...          0.3220                  0.06386
373       20.640         17.35  ...          0.2689                  0.07055
161       19.190         15.94  ...          0.2443                  0.06251
101        6.981         13.43  ...          0.2932                  0.09382
230       17.050         19.08  ...          0.3109                  0.09061

[455 rows x 30 columns]

In [26]:
print(y_train)

199    M
484    B
435    M
379    M
312    B
      ..
533    M
373    M
161    M
101    B
230    M
Name: diagnosis, Length: 455, dtype: object

In [19]:
print(y_test)

346    B
316    B
384    B
123    B
182    M
      ..
263    M
229    M
181    M
381    B
518    B
Name: diagnosis, Length: 114, dtype: object

## Scaling

In [30]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [31]:
print(X_train)

[[ 0.1035752   0.237719    0.11823327 ...  1.10075405  3.08566071
   1.10732583]
 [ 0.47074422 -1.8536139   0.46403796 ...  0.50840079 -0.52292282
  -0.06768684]
 [-0.03124467  0.09736109 -0.0220028  ...  1.08387352  0.49918053
   1.36053534]
 ...
 [ 1.46324798 -0.76350078  1.4419453  ...  1.00714382 -0.71025366
  -1.23124479]
 [-2.0389134  -1.35066471 -1.99154981 ... -1.71982962  0.09329704
   0.65637177]
 [ 0.84938728 -0.02896103  0.90513659 ...  2.18264278  0.38415282
   0.46284736]]

## Encoding Categorical

In [32]:
encoder = LabelEncoder()

y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [33]:
y_train

array([1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1])

## Covert numpy array to Tensor

In [34]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_test)
y_test_tensor = torch.from_numpy(y_test)

In [36]:
print(X_train_tensor)

tensor([[ 0.1036,  0.2377,  0.1182,  ...,  1.1008,  3.0857,  1.1073],
        [ 0.4707, -1.8536,  0.4640,  ...,  0.5084, -0.5229, -0.0677],
        [-0.0312,  0.0974, -0.0220,  ...,  1.0839,  0.4992,  1.3605],
        ...,
        [ 1.4632, -0.7635,  1.4419,  ...,  1.0071, -0.7103, -1.2312],
        [-2.0389, -1.3507, -1.9915,  ..., -1.7198,  0.0933,  0.6564],
        [ 0.8494, -0.0290,  0.9051,  ...,  2.1826,  0.3842,  0.4628]],
       dtype=torch.float64)

# Defining the model

In [39]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

## Important Parameter

In [42]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

 > 4 Steps :

 * Define Loop
 * Forward Pass
 * Backward Pass
 * Parameters update

In [43]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.8967702603372163
Epoch: 2, Loss: 3.7814889969400833
Epoch: 3, Loss: 3.664758827961337
Epoch: 4, Loss: 3.5419228967234426
Epoch: 5, Loss: 3.413054912798033
Epoch: 6, Loss: 3.2796291993419158
Epoch: 7, Loss: 3.138334452915872
Epoch: 8, Loss: 2.9926018479810668
Epoch: 9, Loss: 2.845524786004212
Epoch: 10, Loss: 2.697038381395663
Epoch: 11, Loss: 2.544342944109584
Epoch: 12, Loss: 2.389694612491069
Epoch: 13, Loss: 2.2322921684791366
Epoch: 14, Loss: 2.078665523057126
Epoch: 15, Loss: 1.9247270335967268
Epoch: 16, Loss: 1.7719134420213127
Epoch: 17, Loss: 1.6257239176434364
Epoch: 18, Loss: 1.4908770122254773
Epoch: 19, Loss: 1.366390263646402
Epoch: 20, Loss: 1.2510540996837332
Epoch: 21, Loss: 1.1514392453933788
Epoch: 22, Loss: 1.0678948268173187
Epoch: 23, Loss: 0.9999342743469504
Epoch: 24, Loss: 0.9461462881071905
Epoch: 25, Loss: 0.9043657358909264

# Model Evaluation

In [44]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5517082214355469